# Generated by Django 2.2.16 on 2020-11-26 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAppVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='e.g. 1.0.0', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid format. Format must be [0-9].[0-9].[0-9]. (e.g. 1.0.0)', regex='^\\d\\.\\d\\.\\d$')], verbose_name='Version')),
                ('in_stores', models.BooleanField(default=False, help_text='Is this the currently available Web-App version in stores?', verbose_name='In Stores?')),
            ],
            options={
                'verbose_name': 'Web-App Version',
                'verbose_name_plural': 'Web-App Versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
